# About this Guide {-}

Houston R Users are hosting a [guided intro workshop](http://www.meetup.com/houstonr/events/234653360/) on November 12, 2016.  This guide is the full version of the short guide handed out at the workshop.  This should be a good reference for reviewing things we covered in person, or for a self-guided introduction to R.

# Welcome to Intro to R

We are very excited you could make it to this Intro to R workshop!  We hope to leave this workshop with some practical practice under our belts working with data in R and the ability to find and understand resources when applying these steps to our own datasets.

## Why R?

R is a programming language designed specifically for statistics.  Because it is a free and open source language, many people have contributed to the R ecosystem.  In addition to being very powerful and expressive for statistical analysis, R has become very popular for doing exploratory data visualization and reporting as well.

## Why not R?

* R is limited in producing highly-customizing and interactive reporting visualizations

  While R is able to produce interactive graphics, maps, and dashboards by leveraging JavaScript, a lot of the more expressive and customized interactive data presentation cannot yet be acheived with R.  The gap is closing quickly however, and you can read more about that [here](./05-appendix).

* R is not as expressive for general tasks such as scraping and crawling

  Additionally, while data-mining, scraping and crawling for data can be done in R, those might be tasks better left to Python if you are already familar with Python.  Otherwise, R can handle your data workflow from data gathering to exploration to analysis to presentation.

* R's ecosystem for machine learning is limited

  For problems in the machine learning, computer vision, and text-analysis (debatably), Python has more comprehensive libraries available.

* R can be slow

  For projects where the data needs to be analyzed or processed very quickly, we will want to consider using [C within R](./05-appendix).

Overall, R is a top choice for data exploration, modelling, analysis, and static graphics.

## What is the scope of this workshop?

This workshop will cover steps and code that can be readily adapted for small to moderate sized datasets.

// will include what is missing from this workshop


## The Plan

Today, we are going to cover:

1. Loading in the data
1. Exploring it
1. Cleaning it
1. Calculating descriptive statistics
1. Visualizing it
1. Modeling it
1. Making a report

We will also cover how to get help and how to learn more about using R.

While we will not be able to cover how to handle a wide variety of different datasets and visualizations, our mentors have a wide range of experiences with using R for energy data, bioinformatics, mapping, natural language processing, and much more!  We hope to get to know you throughout the workshop and share domain specific experiences with you.
